import type { AppProps } from "next/app"

// Utils
import { AppProvider } from "@utils/context/AppContext"
import { PageProvider } from "@utils/context/PageContext"
import { ShowcaseProvider } from "@components/showcase/Context"

// Styles
import GlobalStyle from "@styles/global"

// Components
import DebugGrid from "@components/utils/DebugGrid/DebugGrid"
import SiteHeader from "@components/site/SiteHeader/SiteHeader"
import SiteFooter from "@components/site/SiteFooter/SiteFooter"
import PageWrapper from "@components/layout/PageWrapper/PageWrapper"
import ShowcaseModal from "@components/showcase/ShowcaseModal/ShowcaseModal"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const App = ({ Component, pageProps, router }: AppProps) => {
  const isHomepage = router.pathname === "/"

  return (
    <>
      <GlobalStyle />

      <AppProvider>
        <DebugGrid />

        <SiteHeader />

        <PageProvider>
          <PageWrapper>
            {isHomepage ? (
              <ShowcaseProvider>
                <ShowcaseModal />

                <Component key={router.pathname} {...pageProps} />
              </ShowcaseProvider>
            ) : (
              <Component key={router.pathname} {...pageProps} />
            )}
          </PageWrapper>
        </PageProvider>

        <SiteFooter />
      </AppProvider>
    </>
  )
}

export default App
