"use client"

import StyledComponentsRegistry from "@/lib/registry"
import GlobalStyle from "@/styles/global"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body>
      <StyledComponentsRegistry>
        <GlobalStyle />
        {children}
      </StyledComponentsRegistry>
    </body>
  </html>
)

export default RootLayout
